server:
  port: 8081

spring:
  application:
    name: gee-provider-depart
  jpa:
    # 指定在Spring容器启动时是否自动建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示其执行的SQL语句，默认false
    show-sql: true
    # 指定应用重启时是否重新创建更新表
    hibernate:
        ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.100.245.182:3306/springcloud?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 1qaz!QAZ



logging:
  # 设置日志输出格式
  pattern:
    console: level-%level %msg%n
  level:
    root: info   # 控制Spring Boot启动时的日志级别

    org.hibernate: info   # 控制hibernate运行时的日志级别
    # 在show-sql为true时，显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时，显示SQL查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace

    com.gee.provider: debug

#eureka 注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
      #defaultZone: http://localhost:8000/eureka,http://localhost:8001/eureka
  instance:
    instance-id: gee-provider-depart-8081

info:
  company.name: www.abc.com
  company.addr: China Beijing
  company.tel: 12345678
  app.name: abc-msc
  app.desc: mic-server-cloud
  author: abc
