server:
  port: 8080

spring:
  application:
    name: gee-consumer-depart

eureka:
  #指定eureka服务中心
  client:
    service-url:
    #  defaultZone: http://localhost:8000/eureka
      defaultZone: http://localhost:8000/eureka,http://localhost:8001/eureka





